# Generated by Django 3.2.7 on 2022-01-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifTitle', models.CharField(blank=None, max_length=120, null=None, verbose_name='Duyuru Başlığı')),
                ('notifDesc', models.TextField(blank=None, null=None, verbose_name='Duyuru İçeriği')),
                ('notifDate', models.DateTimeField(auto_now=True, verbose_name='Duyuru Yayım Tarihi')),
            ],
        ),
    ]
