# Generated by Django 3.2.7 on 2022-01-30 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursevideo_slug'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=None, max_length=120, null=None, verbose_name='Ödev Başlığı')),
                ('desc', models.TextField(blank=None, null=None, verbose_name='Ödev İçeriği')),
                ('startdate', models.DateTimeField(verbose_name='Ödev Başlangıç Tarihi')),
                ('enddate', models.DateTimeField(verbose_name='Ödev Başlangıç Tarihi')),
                ('homeworklist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='homework_list', to='courses.courselist')),
            ],
        ),
    ]
