# Generated by Django 3.2.7 on 2022-01-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armatitle', models.CharField(default='Arma Başlığı', max_length=120, verbose_name='Arma Başlığı')),
                ('armaimage', models.ImageField(default='armaimage/armatemplate.png', upload_to='armaimage/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name_surname', models.CharField(default='AD SOYAD', max_length=120, verbose_name='İsim ve Soyisim')),
                ('unitname', models.CharField(default='BİRİM İSMİ', max_length=60, verbose_name='Bulunulan Birim')),
                ('pfp', models.ImageField(default='userpfp/frzallogo.png', upload_to='userpfp/')),
                ('classname', models.CharField(max_length=50, verbose_name='Okul Sınıfı')),
                ('schoolno', models.IntegerField(verbose_name='Okul Numarası')),
                ('birthday', models.DateField(verbose_name='Doğum Tarihi')),
                ('place', models.CharField(max_length=120, verbose_name='Yaşadığı Anlık Yer')),
                ('allergy', models.CharField(max_length=120, verbose_name='Alerji Durumu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accprofile', serialize=False, to='auth.user')),
                ('arma', models.ManyToManyField(to='accounts.Arma')),
            ],
        ),
    ]
