# Generated by Django 3.2.7 on 2022-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courselist_desc'),
        ('accounts', '0004_alter_arma_armaimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lecturelist',
            field=models.ManyToManyField(blank=True, to='courses.CourseList'),
        ),
    ]
