# Generated by Django 3.2.7 on 2022-01-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursevideo_slug'),
        ('accounts', '0005_userprofile_lecturelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='complatedvideo',
            field=models.ManyToManyField(blank=True, to='courses.CourseVideo'),
        ),
    ]
