# Generated by Django 3.2.7 on 2022-01-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Yeni Kurs Listesi', max_length=120, verbose_name='Kurs Listesi İsmi')),
                ('headings', models.TextField(help_text='Üniteleri Virgül Kullanarak ve Alt Satıra Geçerek Ayırınız!', verbose_name='Kurs Üniteleri')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
