# Generated by Django 3.2.7 on 2022-01-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselist',
            name='headings',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='attach',
            field=models.URLField(default='', verbose_name='İlgili Dosya Linkleri'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='courselist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.courselist'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='desc',
            field=models.TextField(default='Bu Ders İçin Açıklamaya Gerek Yoktur!', verbose_name='Ders Açıklaması'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='driveid',
            field=models.CharField(default='0000x', max_length=200, verbose_name='Video Drive Id'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name',
            field=models.CharField(default='Adlandırılmamış Video', max_length=180, verbose_name='Video İsmi'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='videoindex',
            field=models.IntegerField(default=999, verbose_name='Oynatma Listesi Index Sırası'),
        ),
        migrations.CreateModel(
            name='CourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUnit', models.CharField(default='Yeni Ünite', max_length=160, verbose_name='Bölüm Adı')),
                ('playlist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.courselist')),
            ],
        ),
    ]
