# Generated by Django 3.2.7 on 2022-01-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220128_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='videoindex',
            field=models.IntegerField(default=999, verbose_name='Oynatma Listesi Index Sırası'),
        ),
    ]
