# Generated by Django 3.2.7 on 2022-01-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursevideo_videoindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
