# Generated by Django 3.2.7 on 2022-01-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courselist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseunits',
            name='playlist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plist_units', to='courses.courselist'),
        ),
    ]
