# Generated by Django 3.2.7 on 2022-01-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220128_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='banner',
            field=models.ImageField(default='courselists/wp1.jpg', upload_to='courselists/', verbose_name='Kurs Kapağını Yükleyiniz'),
        ),
    ]
