# Generated by Django 3.2.7 on 2022-01-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courselist_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='desc',
            field=models.TextField(default='Açıklama Eklenmemiştir!', verbose_name='Eğitim Seti Açıklaması'),
        ),
    ]
