# Generated by Django 3.2.7 on 2022-01-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courselist_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
