# Generated by Django 3.2.7 on 2022-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursevideo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='attach',
            field=models.URLField(blank=True, default='', null=True, verbose_name='İlgili Dosya Linki'),
        ),
    ]
